[package]
name = "data_market-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "Ovidiu Damian - Itheum","Bucur David - Itheum"]

[dev-dependencies]

[dependencies.data_market]
path = ".."

[dependencies.elrond-wasm]
version = "0.38.0"

[dependencies.elrond-wasm-debug]
version = "0.38.0"
