// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           36
// Async Callback (empty):               1
// Total number of exported functions:  38

#![no_std]
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    data_market
    (
        initializeContract
        setDiscounts
        setFees
        setClaimsContract
        setRoyaltiesClaimToken
        addAcceptedToken
        addAcceptedPayment
        setIsPaused
        addOffer
        changeOfferPrice
        cancelOffer
        acceptOffer
        setTreasuryAddress
        setAdministrator
        getOffers
        getUserListedOffers
        getAcceptedTokens
        getAcceptedTokenPayments
        getDiscountFeePercentageBuyer
        getDiscountFeePercentageSeller
        getPercentageCutFromSeller
        getPercentageCutFromBuyer
        getEmptyOfferIndexes
        getHighestOfferIndex
        getIsPaused
        getTreasuryAddress
        getClaimsAddress
        getRoyaltiesClaimToken
        getAdministrator
        getRequirements
        viewPagedOffers
        getUserTotalOffers
        viewUserListedOffers
        viewOffers
        viewOffer
        numberOfOffers
    )
}

multiversx_sc_wasm_adapter::empty_callback! {}
